### ISSUE TITLE
App crashes with UNKNOWN_ERROR for Add Validator transaction with StakeableLock

### ISSUE THREAD

**Issue by defunctzombie** [obsidiansystems/ledger-app-avalanche#39]
When sending an add-validator transaction which contains StakeableLockIn and StakeableLockOut the signing process terminates abruptly after clicking "next" on the first screen; the first screen displays the "Sign AddValidator" text. The signing process returns back to the Avalanche app home screen.

** I'm working on making a simple reproducing test case which I can share yet wanted to post the issue to start discussion.

**Comment by ApolloUnicorn** [comment]
@defunctzombie where you using wallet.avax.network or the [CLI](https://github.com/obsidiansystems/avalanche-wallet-cli) ?

I am curious about what the CLI would spit out as the error

**Comment by jonored** [comment]
Also, what was the numeric error code provided? a variety of exceptions get marked as unknown on the host side, but still display useful error codes.

**Comment by defunctzombie** [comment]
@ApolloUnicorn we were using our own tool which builds a transaction using avalanchejs (v3.0.5) and sends to the ledger via @obsidiansystems/hw-app-avalanche (v0.2.2) over transport @ledgerhq/hw-transport-node-hid-noevents (v5.29.0).

Worth noting the tool works for add-validator where SECPTransferInput is used, however we had to fall-back to signHash for add-validator with StakeableLock due to the error described in this issue.

@jonored the full error message we got from the hw-app-avalanche layer is:
```
Error: Ledger device: UNKNOWN_ERROR (0x9405)
```

**Comment by jonored** [comment]
0x9405 is a simple rejection from the validation and display on the ledger; we might not have support for parsed signing with StakeableLock at this time.

**Comment by ApolloUnicorn** [comment]
@defunctzombie I'd be very interested in the repo case you mentioned, when available.

**Comment by artichikin** [comment]
I can also get this exact error by attempting to delegate to a node. Currently using v0.4.0. Is this simply not supported via ledger app yet?

**Comment by ApolloUnicorn** [comment]
Fixed in #53

**Comment by ApolloUnicorn** [comment]
Fixed in https://github.com/obsidiansystems/ledger-app-avalanche/releases/tag/v0.4.3
