### ISSUE TITLE
apdu_fixed and hash question

### ISSUE THREAD

**Issue by cevatbostancioglu** [obsidiansystems/ledger-app-avalanche#42]
device: ledger nano s
firmware: 1.6.1
environment: ubuntu 20.04

i cant find any apdu_fixed application in github/google/repo.
How do you guys getting that application ? 

my other question is: 
on computer terminal:
Generated random root public key : b'04a70ee72b67
Application full hash : c7246680bee7a36f8f6a64b56a648dd55ba21813077f3eedc5cfa3bab8092e05
on ledger screen:
identifier starts with 9526B4C0FA...C5DA
Code identifier: D73BE1EC....DAFC87

Why this hash variables are different?

**Comment by ApolloUnicorn** [comment]
@cevatbostancioglu 

> i cant find any apdu_fixed application
I think what you are looking for is https://github.com/obsidiansystems/ledger-app-avalanche/blob/master/src/apdu.c

> Why this hash variables are different?
The ledger screen will only show that hash if you load the app from source. It's mainly a way to ensure you have the correct version. The "shown on screen" is what you should confirm after you load the app.
